### ISSUE TITLE
Subtitles not found

### ISSUE THREAD

**Issue by iamfreee** [cguZZman/onedrive-kodi-addon#3] opened 2017-05-22 22:22 UTC
Hi, i am having this problem again.

I have these files:
`How I Met Your Mother S07E01 The Best Man (1080p x265 Joy).mkv`
`How I Met Your Mother S07E01 The Best Man (1080p x265 Joy).srt`

And the addon is not finding the subtitle to play 😢 

![image](https://cloud.githubusercontent.com/assets/1500881/26330769/69ba59d8-3f45-11e7-8ed8-9a653e4027a2.png)

Version 1.2.0

Thanks!

**Comment by cguZZman** [comment] 2017-05-23 03:14
Hey, thanks for the bug report. I confirmed the issue.
Looks like the new endpoint url encoding doesn't work exactly the same as the previous one.
I'll include the fix in the next release.

If you want the fix now, go to your kodi installation folder (`<kodi_folder>/addons/plugin.onedrive/`) and modify the `addon.xml` file in the line 657:

You will find this:
`subtitle_path = parent_path+'/'+urllib.quote_plus(utils.Utils.str(subtitle_name))`

just replace that line for this one:
`subtitle_path = parent_path+'/'+urllib.quote(utils.Utils.str(subtitle_name))`

Save the modification and that's it. It should be working fine.

**Comment by iamfreee** [comment] 2017-05-23 10:05
Thanks @cguZZman !

**Comment by pcasalinho** [comment] 2017-05-28 20:38
subs with the language code don't work... [filename.en.srt] Removed the .en and it Worked!
Thanks for all the work!

**Comment by cguZZman** [comment] 2017-05-30 21:12
That's correct @pcasalinho, the language code needs to be removed. The str filename must be the same as the video filename.

**Comment by cguZZman** [comment] 2017-05-30 21:13
Issue fixed in v1.3.0.

**Closed by cguZZman** 2017-05-30 21:13 UTC
Labels: bug
